@Catalog.API_HostAddress = http://localhost:5077

GET {{Catalog.API_HostAddress}}/api/products
Accept: application/json

###

POST {{Catalog.API_HostAddress}}/api/products/DiscountPrice
Content-Type: application/json

{
  "productId": "53ad4035-c80c-4595-aae1-c9ce0505bb4b",
  "discountRate": 0.15
}

###
GET {{Catalog.API_HostAddress}}/api/products/dell
Accept: application/json